
import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname=" + dbname + " user=" + user + " password=" + password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")

    _global = []
    
    rows = cur.fetchall()
    keys_seen = set()
    for row in rows:
        row = dict(row)
        key = (row['cust'])
        if key not in keys_seen:
            keys_seen.add(key)
            h_row = {'cust': row['cust']}
            h_row['sum_1_quant'] = 0
            h_row['sum_2_quant'] = 0
            h_row['avg_1_quant'] = 0
            h_row['avg_2_quant'] = 0
            h_row['count_1'] = 0
            h_row['count_2'] = 0
            
            _global.append(h_row)

    
    for sc in range(1, 2 + 1):
        predicate = ["(x['prod']=='Apple')", "(x['prod']=='Fish')"][sc - 1]
        print(f"Evaluating scan {sc}: {predicate}")

        for row in rows:
            row = dict(row)
            x = row
            if eval(predicate):
                for h_row in _global:
                    if all(h_row[g] == row[g] for g in ['cust']):
                        for agg in ['sum_1_quant', 'sum_2_quant', 'avg_1_quant', 'avg_2_quant', 'count_1', 'count_2']:
                            if agg.startswith(f"sum_{sc}") and 'quant' in row:
                                h_row[agg] += row['quant']
                            elif agg.startswith(f"count_{sc}"):
                                h_row[agg] += 1
                            elif agg.startswith(f"min_{sc}") and 'quant' in row:
                                h_row[agg] = min(h_row[agg], row['quant'])
                            elif agg.startswith(f"max_{sc}") and 'quant' in row:
                                h_row[agg] = max(h_row[agg], row['quant'])
    
    
    for h_row in _global:
        for agg in ['sum_1_quant', 'sum_2_quant', 'avg_1_quant', 'avg_2_quant', 'count_1', 'count_2']:
            if agg.startswith("avg_"):
                parts = agg.split("_")
                sc = parts[1]
                base = "_".join(parts[2:])
                sum_key = f"sum_{sc}_{base}"
                count_key = f"count_{sc}"
                if sum_key in h_row and count_key in h_row and h_row[count_key] != 0:
                    h_row[agg] = h_row[sum_key] / h_row[count_key]
    

    print("MF Structure After Aggregation:")
    for row in _global:
        print(row)
    

def main():
    query()

if __name__ == "__main__":
    main()
