
import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    rows = cur.fetchall()
    keys_seen = set()
    for row in rows:
        row = dict(row)
        key = (row['prod'])
        if key not in keys_seen:
            keys_seen.add(key)
            h_row = {'prod': row['prod']}
            h_row['sum_x_quant'] = 0
            h_row['sum_y_quant'] = 0
            h_row['sum_z_quant'] = 0
            _global.append(h_row)

    print(" MF Structure Initialized:")
    for row in _global:
        print(row)
    

def main():
    query()
    
if __name__ == "__main__":
    main()
    