
import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    rows = cur.fetchall()
    keys_seen = set()
    for row in rows:
        row = dict(row)
        key = (row['cust'])
        if key not in keys_seen:
            keys_seen.add(key)
            h_row = {'cust': row['cust']}
            h_row['sum_ny_quant'] = 0
            h_row['count_ny'] = 0
            h_row['avg_ny'] = 0
            h_row['min_ny'] = float('inf')
            h_row['max_ny'] = float('-inf')
            
            _global.append(h_row)

    print(" MF Structure Initialized:")
    for row in _global:
        print(row)

    print("\n Aggregate Summary:")
    agg_keys = [k for k in _global[0].keys() if any(a in k for a in ['sum', 'count', 'avg', 'min', 'max'])]
    for key in agg_keys:
        values = [row[key] for row in _global if isinstance(row[key], (int, float))]
        if values:
            print(f"{key}: min = {min(values)}, max = {max(values)}")
    

def main():
    query()
    
if __name__ == "__main__":
    main()
