import subprocess


def parse_phi_from_file(filepath):
    phi = {
        "attributes": [],
        "gv_count": 0,
        "gv": [],
        "agg_func": [],
        "gv_predicates": [],
        "having": ""
    }

    key_map = {
        "S": "attributes",
        "n": "gv_count",
        "V": "gv",
        "F": "agg_func",
        "sig": "gv_predicates",
        "G": "having"
    }

    with open(filepath, "r") as f:
        lines = f.read().strip().split("\n")

    for line in lines:
        if not line.strip():
            continue
        key, value = line.split(":")
        key = key.strip()
        value = value.strip()

        mapped_key = key_map.get(key)
        if not mapped_key:
            raise ValueError(f"Unknown key: {key}")

        if mapped_key == "gv_count":
            phi[mapped_key] = int(value)
        elif mapped_key == "having":
            phi[mapped_key] = value
        else:
            phi[mapped_key] = [v.strip() for v in value.split(",")]

    return phi


def main():
    phi = parse_phi_from_file("C:/Users/Harsh Bhikadiya/OneDrive/Desktop/Csem2/Agile/DBMS2_Spring_2025/mf_input.txt")

    gv_attrs = phi["gv"]
    agg_attrs = phi["agg_func"]

    key_tuple_expr = ", ".join([f"row['{g}']" for g in gv_attrs])
    gv_dict_expr = ", ".join([f"'{g}': row['{g}']" for g in gv_attrs])

    agg_init_lines = ""
    for agg in agg_attrs:
        if "min" in agg:
            agg_init_lines += f"h_row['{agg}'] = float('inf')\n            "
        elif "max" in agg:
            agg_init_lines += f"h_row['{agg}'] = float('-inf')\n            "
        else:
            agg_init_lines += f"h_row['{agg}'] = 0\n            "

    # Dynamically generate the Python logic for _generated.py
    body = f"""
    rows = cur.fetchall()
    keys_seen = set()
    for row in rows:
        row = dict(row)
        key = ({key_tuple_expr})
        if key not in keys_seen:
            keys_seen.add(key)
            h_row = {{{gv_dict_expr}}}
            {agg_init_lines}
            _global.append(h_row)

    print(" MF Structure Initialized:")
    for row in _global:
        print(row)

    print("\\n Aggregate Summary:")
    agg_keys = [k for k in _global[0].keys() if any(a in k for a in ['sum', 'count', 'avg', 'min', 'max'])]
    for key in agg_keys:
        values = [row[key] for row in _global if isinstance(row[key], (int, float))]
        if values:
            print(f"{{key}}: min = {{min(values)}}, max = {{max(values)}}")
    """

    # Template string for the generated Python file
    tmp = f'''
import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}

def main():
    query()
    
if __name__ == "__main__":
    main()
'''

    # Write to _generated.py and execute it
    with open("_generated.py", "w") as f:
        f.write(tmp)

    subprocess.run(["python", "_generated.py"])


if __name__ == "__main__":
    main()
