import subprocess


def parse_phi_from_file(filepath):
    phi = {
        "attributes": [],
        "gv_count": 0,
        "gv": [],
        "agg_func": [],
        "gv_predicates": [],
        "having": ""
    }

    key_map = {
        "S": "attributes",
        "n": "gv_count",
        "V": "gv",
        "F": "agg_func",
        "sig": "gv_predicates",
        "G": "having"
    }

    with open(filepath, "r") as f:
        lines = f.read().strip().split("\n")

    for line in lines:
        if not line.strip():
            continue
        key, value = line.split(":")
        key = key.strip()
        value = value.strip()

        mapped_key = key_map.get(key)
        if not mapped_key:
            raise ValueError(f"Unknown key: {key}")

        if mapped_key == "gv_count":
            phi[mapped_key] = int(value)
        elif mapped_key == "having":
            phi[mapped_key] = value
        else:
            phi[mapped_key] = [v.strip() for v in value.split(",")]

    return phi


def main():
    # Step 1: Read phi input
    phi = parse_phi_from_file("C:/Users/Harsh Bhikadiya/OneDrive/Desktop/Csem2/DBMS/DBMS2_Spring_2025/mf_input.txt")

    # Step 2: Build body dynamically based on gv and agg_func
    gv_attrs = phi["gv"]                          # e.g. ['prod']
    agg_attrs = phi["agg_func"]                   # e.g. ['sum_x_quant', 'sum_y_quant', 'sum_z_quant']

    key_tuple_expr = ", ".join([f"row['{g}']" for g in gv_attrs])
    gv_dict_expr = ", ".join([f"'{g}': row['{g}']" for g in gv_attrs])
    agg_init_lines = "\n            ".join([f"h_row['{agg}'] = 0" for agg in agg_attrs])

    body = f"""
    rows = cur.fetchall()
    keys_seen = set()
    for row in rows:
        row = dict(row)
        key = ({key_tuple_expr})
        if key not in keys_seen:
            keys_seen.add(key)
            h_row = {{{gv_dict_expr}}}
            {agg_init_lines}
            _global.append(h_row)

    print(" MF Structure Initialized:")
    for row in _global:
        print(row)
    """

    # Step 3: Generate the actual executable script
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}

def main():
    query()
    
if __name__ == "__main__":
    main()
    """

    # Step 4: Write and execute the generated script
    with open("_generated.py", "w") as f:
        f.write(tmp)

    subprocess.run(["python", "_generated.py"])


# THIS LINE WAS WRONG BEFORE
if __name__ == "__main__":
    main()
